schema_version = "1.0.0"

id = "physics_export"
version = "1.0.8"
name = "Physics Export"
tagline = "Exports objects and physics constraints to JSON"
maintainer = "Antoine Boucher <antoine@antoineboucher.info>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "GPL-3.0-or-later"
]

website = "https://github.com/ETSTribology/BlenderPluginSimulation"
tags = ["Object", "Physics", "Export"]

[permissions]
files = "Required for reading and writing files during export"
network = "Required for accessing online resources or services"

[build]
wheels = [
  "./wheels/certifi-2024.8.30-py3-none-any.whl",
  "./wheels/charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl",
  "./wheels/charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl",
  "./wheels/contourpy-1.3.0-cp312-cp312-win_amd64.whl",
  "./wheels/cycler-0.12.1-py3-none-any.whl",
  "./wheels/fonttools-4.54.1-cp312-cp312-win_amd64.whl",
  "./wheels/idna-3.10-py3-none-any.whl",
  "./wheels/kiwisolver-1.4.7-cp312-cp312-win_amd64.whl",
  "./wheels/markdown_it_py-3.0.0-py3-none-any.whl",
  "./wheels/matplotlib-3.9.2-cp312-cp312-win_amd64.whl",
  "./wheels/mdurl-0.1.2-py3-none-any.whl",
  "./wheels/meshio-5.3.5-py3-none-any.whl",
  "./wheels/numpy-1.26.0-cp312-cp312-win_amd64.whl",
  "./wheels/numpy-2.1.2-cp312-cp312-win_amd64.whl",
  "./wheels/packaging-24.1-py3-none-any.whl",
  "./wheels/pillow-10.4.0-cp312-cp312-win_amd64.whl",
  "./wheels/pillow-11.0.0-cp312-cp312-win_amd64.whl",
  "./wheels/platformdirs-4.3.6-py3-none-any.whl",
  "./wheels/pooch-1.8.2-py3-none-any.whl",
  "./wheels/pygments-2.18.0-py3-none-any.whl",
  "./wheels/pyparsing-3.1.4-py3-none-any.whl",
  "./wheels/pyparsing-3.2.0-py3-none-any.whl",
  "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
  "./wheels/pyvista-0.44.1-py3-none-any.whl",
  "./wheels/requests-2.32.3-py3-none-any.whl",
  "./wheels/rich-13.9.2-py3-none-any.whl",
  "./wheels/scipy-1.14.1-cp312-cp312-win_amd64.whl",
  "./wheels/scooby-0.10.0-py3-none-any.whl",
  "./wheels/six-1.16.0-py2.py3-none-any.whl",
  "./wheels/tetgen-0.6.5-cp312-cp312-win_amd64.whl",
  "./wheels/trimesh-4.4.9-py3-none-any.whl",
  "./wheels/trimesh-4.5.0-py3-none-any.whl",
  "./wheels/typing_extensions-4.12.2-py3-none-any.whl",
  "./wheels/urllib3-2.2.3-py3-none-any.whl",
  "./wheels/vtk-9.3.1-cp312-cp312-win_amd64.whl"
]
